//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbfcClient.NbfcService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FanControlInfo", Namespace="http://schemas.datacontract.org/2004/07/StagWare.FanControl.Service")]
    [System.SerializableAttribute()]
    public partial class FanControlInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CpuTemperatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbfcClient.NbfcService.FanStatus[] FanStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInitializedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectedConfigField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CpuTemperature {
            get {
                return this.CpuTemperatureField;
            }
            set {
                if ((this.CpuTemperatureField.Equals(value) != true)) {
                    this.CpuTemperatureField = value;
                    this.RaisePropertyChanged("CpuTemperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbfcClient.NbfcService.FanStatus[] FanStatus {
            get {
                return this.FanStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.FanStatusField, value) != true)) {
                    this.FanStatusField = value;
                    this.RaisePropertyChanged("FanStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInitialized {
            get {
                return this.IsInitializedField;
            }
            set {
                if ((this.IsInitializedField.Equals(value) != true)) {
                    this.IsInitializedField = value;
                    this.RaisePropertyChanged("IsInitialized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedConfig {
            get {
                return this.SelectedConfigField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedConfigField, value) != true)) {
                    this.SelectedConfigField = value;
                    this.RaisePropertyChanged("SelectedConfig");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FanStatus", Namespace="http://schemas.datacontract.org/2004/07/StagWare.FanControl.Service")]
    [System.SerializableAttribute()]
    public partial class FanStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutoControlEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CriticalModeEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CurrentFanSpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FanDisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FanSpeedStepsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TargetFanSpeedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoControlEnabled {
            get {
                return this.AutoControlEnabledField;
            }
            set {
                if ((this.AutoControlEnabledField.Equals(value) != true)) {
                    this.AutoControlEnabledField = value;
                    this.RaisePropertyChanged("AutoControlEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CriticalModeEnabled {
            get {
                return this.CriticalModeEnabledField;
            }
            set {
                if ((this.CriticalModeEnabledField.Equals(value) != true)) {
                    this.CriticalModeEnabledField = value;
                    this.RaisePropertyChanged("CriticalModeEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CurrentFanSpeed {
            get {
                return this.CurrentFanSpeedField;
            }
            set {
                if ((this.CurrentFanSpeedField.Equals(value) != true)) {
                    this.CurrentFanSpeedField = value;
                    this.RaisePropertyChanged("CurrentFanSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FanDisplayName {
            get {
                return this.FanDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FanDisplayNameField, value) != true)) {
                    this.FanDisplayNameField = value;
                    this.RaisePropertyChanged("FanDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FanSpeedSteps {
            get {
                return this.FanSpeedStepsField;
            }
            set {
                if ((this.FanSpeedStepsField.Equals(value) != true)) {
                    this.FanSpeedStepsField = value;
                    this.RaisePropertyChanged("FanSpeedSteps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TargetFanSpeed {
            get {
                return this.TargetFanSpeedField;
            }
            set {
                if ((this.TargetFanSpeedField.Equals(value) != true)) {
                    this.TargetFanSpeedField = value;
                    this.RaisePropertyChanged("TargetFanSpeed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NbfcService.IFanControlService")]
    public interface IFanControlService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFanControlService/SetTargetFanSpeed")]
        void SetTargetFanSpeed(float value, int fanIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFanControlService/GetFanControlInfo", ReplyAction="http://tempuri.org/IFanControlService/GetFanControlInfoResponse")]
        NbfcClient.NbfcService.FanControlInfo GetFanControlInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFanControlService/Restart", ReplyAction="http://tempuri.org/IFanControlService/RestartResponse")]
        bool Restart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFanControlService/Start", ReplyAction="http://tempuri.org/IFanControlService/StartResponse")]
        bool Start();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFanControlService/Stop")]
        void Stop();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFanControlService/SetConfig")]
        void SetConfig(string uniqueConfigId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFanControlServiceChannel : NbfcClient.NbfcService.IFanControlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FanControlServiceClient : System.ServiceModel.ClientBase<NbfcClient.NbfcService.IFanControlService>, NbfcClient.NbfcService.IFanControlService {
        
        public FanControlServiceClient() {
        }
        
        public FanControlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FanControlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FanControlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FanControlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetTargetFanSpeed(float value, int fanIndex) {
            base.Channel.SetTargetFanSpeed(value, fanIndex);
        }
        
        public NbfcClient.NbfcService.FanControlInfo GetFanControlInfo() {
            return base.Channel.GetFanControlInfo();
        }
        
        public bool Restart() {
            return base.Channel.Restart();
        }
        
        public bool Start() {
            return base.Channel.Start();
        }
        
        public void Stop() {
            base.Channel.Stop();
        }
        
        public void SetConfig(string uniqueConfigId) {
            base.Channel.SetConfig(uniqueConfigId);
        }
    }
}
